# Generated by Django 3.1.2 on 2020-10-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
