# Generated by Django 3.1.2 on 2021-01-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_auto_20201027_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
